### ISSUE TITLE
chalice deploy command failing with ResourceConflictException UpdateFunctionConfiguration  exception

### ISSUE THREAD

**Issue by kraj007** [aws/chalice#1872]
i am deploying the api gateway using chalice command. Its failing with error 
"botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the UpdateFunctionConfiguration operation: The operation cannot be performed at this time. An update is in progress for resource".

command : chalice deploy --stage staging --profile staging --no-autogen-policy

'Creating deployment package.\n2022-01-20 13:30:17,341 - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials\n/usr/lib64/python3.7/zipfile.py:1506: UserWarning: Duplicate name: 'chalice/__init__.py'\n  return self._open_to_write(zinfo, force_zip64=force_zip64)\n/usr/lib64/python3.7/zipfile.py:1506: UserWarning: Duplicate name: 'chalice/app.py'\n  return self._open_to_write(zinfo, force_zip64=force_zip64)\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/chalice/deploy/deployer.py\", line 376, in deploy\n    return self._deploy(config, chalice_stage_name)\n  File \"/usr/local/lib/python3.7/site-packages/chalice/deploy/deployer.py\", line 392, in _deploy\n    self._executor.execute(plan)\n  File \"/usr/local/lib/python3.7/site-packages/chalice/deploy/executor.py\", line 43, in execute\n    self._default_handler)(instruction)\n  File \"/usr/local/lib/python3.7/site-packages/chalice/deploy/executor.py\", line 55, in _do_apicall\n    result = method(**final_kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/chalice/awsclient.py\", line 881, in update_function\n    layers=layers\n  File \"/usr/local/lib/python3.7/site-packages/chalice/awsclient.py\", line 953, in _update_function_config\n    max_attempts=self.LAMBDA_CREATE_ATTEMPTS\n  File \"/usr/local/lib/python3.7/site-packages/chalice/awsclient.py\", line 1841, in _call_client_method_with_retries\n    response = method(**kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/botocore/client.py\", line 676, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the UpdateFunctionConfiguration operation: The operation cannot be performed at this time. An update is in progress for resource : arn:aws:lambda:us-west-2:XXXXXXXXXX:function:staging-lambda-staging

This seems to be some internal issue with chalice command.
Chalice is trying to create lambda and while updating few configurations its failing stating lambda function already in progress.

We cant have any control here as its failing in chalice deploy command.

**Comment by jamesls** [comment]
Looks like you are using an older version of Chalice.  This was fixed in #1732 which was first released in version 1.23.0 of Chalice, so if you upgrade to the latest version this should resolve your issue.

**Comment by kraj007** [comment]
Hello @jamesls I am already using chalice==1.26.4 in my deployments. Still facing this issue. Do you have any idea why this is happening with this version ?

**Comment by Aryan-S13** [comment]
If anyone looking into this. This is a problem with using chalice deploy in github actions. 
Workaround is to first deploy through local shell so the generated deployment json files are carried to the git branch after you commit them and then run the actions workflow.

Real problem is syncing the created json files in github actions when chalice deployment happens other wise on every subsequent deployment it will give conflicts with existing AWS resources. 

I request to re-open this issue and have a solution that is long termed and easy to use for all.
